name: Check vulnerability
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  audit:
    name: Vulnerability check step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Setup cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v5
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.4-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php8.4-composer-latest-

      - name: Update composer
        run: composer self-update

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Security audit
        run: |
          composer audit \
            --no-dev \
            --abandoned="report" \
            --ignore-severity="low" \
            --format="json" \
            --no-ansi \
            > /tmp/security-check.json

      - name: Upload security check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-check
          path: /tmp/security-check.json
